name: Build Docker container

on: [ workflow_dispatch ]

jobs:
  build_container:
    name: Build container
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}

      - name: Build x64 binary
        run: mkdir build && cd build && cmake .. && cmake --build . --parallel 2 --target sqfvm
        env:
          CC: clang
          CXX: clang++

      - name: Sanity check
        run: build/sqfvm --version

      - name: Move binary to docker directory
        run: mv build/sqfvm docker/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/sqfvm:latest
